name: Build Flutter Web

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --verbose
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
        
    - name: Upload Web Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/